name: bayesNP-env
channels:
- conda-forge
dependencies:
- python
- numpy
- scipy
- matplotlib
- pandas
- seaborn
- jupyter
- nbdime
- emcee
- corner
- mkl-service
- scikit-learn
- scikit-image
- pip
- pip:
  - prettyplease

